### ISSUE TITLE
请问具体配置及系统版本是？...可否告知

### ISSUE THREAD

**Issue by krinm** [lc5900/lc5900-OpenCore_P150SMA#1]
请问具体配置及系统版本是？...可否告知

**Comment by lc5900** [comment]
I7-4900MQ
HD4600&GTX970M(双显卡无法驱动已屏蔽独显)
ALC892
KILLER N1202(AR5B22/AR9462)
RTL8111
BigSur beta2
理论上P15xsm/sma和p17xsm/sma应该都可以通用

**Comment by krinm** [comment]
> I7-4900MQ
> HD4600&GTX970M(双显卡无法驱动已屏蔽独显)
> ALC892
> KILLER N1202(AR5B22/AR9462)
> RTL8111
> BigSur beta2
> 理论上P15xsm/sma和p17xsm/sma应该都可以通用

好的～谢谢您～
